### PR TITLE
CMake required version: from 3.14 to 3.13.

### PR DESCRIPTION
**Pull request by mm-s**
Version of CMake shipped by Debian Buster is 3.13.
I tested the procedure README.manual (preparing _build directory) and gave no issues.

### CODE REVIEW

**Comment by gimer** [comment]
Have you tried conan? downgrading should result in lots of warnings from boost due to old FindBoost.cmake

**Comment by mm-s** [comment]
> Have you tried conan? downgrading should result in lots of warnings from boost due to old FindBoost.cmake

I haven't. I was going through README.manual.
I understood conan is meant to be used by devops to feed the sw release pipeline, and alternative way of building that depends on external systems. (I may be wrong)
Is the manual howto deprecated?

**Comment by Jaguar0625** [comment]
> Is the manual howto deprecated?

No, but we don't want to require one cmake version for manual and another for conan. We'd like to use same cmake version for both.

**Comment by mm-s** [comment]
So is this change going ahead? or is anything else that is pending?

**Comment by mm-s** [comment]
> Have you tried conan? downgrading should result in lots of warnings from boost due to old FindBoost.cmake

The change is about allowing to compile with an older version of CMake, if 3.13 successfully compile I can't guess a reason for requiring a newer version.

**Comment by gimer** [comment]
> The change is about allowing to compile with an older version of CMake, if 3.13 successfully compile I can't guess a reason for requiring a newer version.

@Jaguar0625 stated the reason: `we don't want to require one cmake version for manual and another for conan. We'd like to use same cmake version for both.`

**Comment by mm-s** [comment]
> > The change is about allowing to compile with an older version of CMake, if 3.13 successfully compile I can't guess a reason for requiring a newer version.
> 
> @Jaguar0625 stated the reason: `we don't want to require one cmake version for manual and another for conan. We'd like to use same cmake version for both.`
> 
> (so either check it's working for both or abandon)

I'll check conan... (I didn't realize that was the missing action, thanks)

**Comment by Jaguar0625** [comment]
please rebase as this is stale now since new project (addressgen) was added

**Comment by mm-s** [comment]
Issues with Boost.
PR abandoned. Debian stable devs must install newer CMake, that's all.

**Pull request closed without merging**
